[tool.black]
line-length = 88
target-version = ['py313']
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.flake8]
exclude = [
    ".git",
    "__pycache__",
    "venv",
    "migrations",
    ".mypy_cache",
    ".pytest_cache"
]
ignore = ["E203", "W503", "E501", "W293"]
max-line-length = 88
extend-ignore = "E226"

[tool.mypy]
python_version = "3.13"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
